export const revenueSeries = [
  { month: "Jan", revenue: 12400, users: 820 },
  { month: "Feb", revenue: 15800, users: 932 },
  { month: "Mar", revenue: 14200, users: 1010 },
  { month: "Apr", revenue: 18900, users: 1180 },
  { month: "May", revenue: 21300, users: 1290 },
  { month: "Jun", revenue: 19700, users: 1340 },
  { month: "Jul", revenue: 24800, users: 1510 },
  { month: "Aug", revenue: 27100, users: 1622 },
];

export const requestsSeries = [
  { day: "Mon", requests: 4200 },
  { day: "Tue", requests: 5100 },
  { day: "Wed", requests: 4800 },
  { day: "Thu", requests: 6200 },
  { day: "Fri", requests: 7100 },
  { day: "Sat", requests: 3900 },
  { day: "Sun", requests: 3400 },
];

export const users = [
  { id: "u1", name: "Amelia Hart", email: "amelia.hart@example.com", role: "Owner", status: "Active", lastActive: "2 hours ago", project: "alumni-api" },
  { id: "u2", name: "Ben Osei", email: "ben.osei@example.com", role: "Admin", status: "Active", lastActive: "5 hours ago", project: "dry-apps-mobile" },
  { id: "u3", name: "Chen Wei", email: "chen.wei@example.com", role: "Developer", status: "Invited", lastActive: "—", project: "dns-portal" },
  { id: "u4", name: "Dara Putri", email: "dara.putri@example.com", role: "Developer", status: "Active", lastActive: "1 day ago", project: "laundry-web" },
  { id: "u5", name: "Farid Hakim", email: "farid.hakim@example.com", role: "Viewer", status: "Suspended", lastActive: "12 days ago", project: "dns-services" },
  { id: "u6", name: "Grace Lim", email: "grace.lim@example.com", role: "Admin", status: "Active", lastActive: "30 min ago", project: "alumni-api" },
  { id: "u7", name: "Hendra Saputra", email: "hendra.s@example.com", role: "Developer", status: "Active", lastActive: "3 hours ago", project: "dry-apps-mobile" },
  { id: "u8", name: "Ines Marchetti", email: "ines.m@example.com", role: "Viewer", status: "Invited", lastActive: "—", project: "dns-portal" },
];

export const invoices = [
  { id: "INV-2026-0148", date: "Aug 24, 2026", plan: "Pro — Monthly", amount: "$25.00", status: "Paid" },
  { id: "INV-2026-0122", date: "Jul 24, 2026", plan: "Pro — Monthly", amount: "$25.00", status: "Paid" },
  { id: "INV-2026-0098", date: "Jun 24, 2026", plan: "Pro — Monthly", amount: "$25.00", status: "Paid" },
  { id: "INV-2026-0071", date: "May 24, 2026", plan: "Pro — Monthly", amount: "$25.00", status: "Paid" },
  { id: "INV-2026-0045", date: "Apr 24, 2026", plan: "Free → Pro upgrade", amount: "$12.50", status: "Refunded" },
  { id: "INV-2026-0019", date: "Mar 24, 2026", plan: "Free", amount: "$0.00", status: "Paid" },
];

export const files = [
  { name: "brand-guidelines.pdf", type: "PDF", size: "4.2 MB", modified: "Today, 10:24 AM", shared: true },
  { name: "onboarding-flow.fig", type: "Figma", size: "18.7 MB", modified: "Yesterday", shared: true },
  { name: "q3-report.xlsx", type: "Sheet", size: "1.1 MB", modified: "Aug 27, 2026", shared: false },
  { name: "database-schema.sql", type: "Code", size: "84 KB", modified: "Aug 25, 2026", shared: false },
  { name: "team-photo.png", type: "Image", size: "6.5 MB", modified: "Aug 21, 2026", shared: true },
  { name: "roadmap-notes.md", type: "Doc", size: "22 KB", modified: "Aug 18, 2026", shared: false },
  { name: "api-contract-v2.docx", type: "Doc", size: "310 KB", modified: "Aug 14, 2026", shared: true },
];

export const notifications = [
  { id: "n1", title: "New order received", desc: "Order #ORD-3391 from Dara Putri", time: "2 min ago", unread: true },
  { id: "n2", title: "Server CPU spike", desc: "alumni-api crossed 85% usage", time: "1 hour ago", unread: true },
  { id: "n3", title: "New message", desc: "Grace Lim sent you a message", time: "3 hours ago", unread: true },
  { id: "n4", title: "Payment received", desc: "Invoice INV-2026-0148 was paid", time: "Yesterday", unread: false },
  { id: "n5", title: "Backup completed", desc: "Daily database backup finished", time: "2 days ago", unread: false },
];

export const products = [
  { id: "p1", name: "Wireless Keyboard Pro", category: "Peripherals", price: "$79.00", stock: 142, sold: 320, status: "Active" },
  { id: "p2", name: "Mechanical Mouse X2", category: "Peripherals", price: "$49.00", stock: 8, sold: 210, status: "Low stock" },
  { id: "p3", name: "27\" 4K Monitor", category: "Displays", price: "$389.00", stock: 34, sold: 96, status: "Active" },
  { id: "p4", name: "USB-C Dock Station", category: "Accessories", price: "$129.00", stock: 0, sold: 155, status: "Out of stock" },
  { id: "p5", name: "Ergonomic Chair", category: "Furniture", price: "$449.00", stock: 21, sold: 58, status: "Active" },
  { id: "p6", name: "Noise Cancelling Headset", category: "Audio", price: "$159.00", stock: 63, sold: 274, status: "Active" },
];

export const orders = [
  { id: "ORD-3391", customer: "Dara Putri", date: "Aug 30, 2026", items: 3, total: "$267.00", status: "Processing" },
  { id: "ORD-3388", customer: "Ben Osei", date: "Aug 29, 2026", items: 1, total: "$79.00", status: "Shipped" },
  { id: "ORD-3379", customer: "Chen Wei", date: "Aug 28, 2026", items: 2, total: "$538.00", status: "Delivered" },
  { id: "ORD-3364", customer: "Amelia Hart", date: "Aug 27, 2026", items: 4, total: "$725.00", status: "Delivered" },
  { id: "ORD-3350", customer: "Farid Hakim", date: "Aug 25, 2026", items: 1, total: "$129.00", status: "Cancelled" },
  { id: "ORD-3341", customer: "Grace Lim", date: "Aug 24, 2026", items: 2, total: "$208.00", status: "Shipped" },
];

export const chatContacts = [
  { id: "c1", name: "Grace Lim", lastMessage: "Sounds good, I'll review the PR today.", time: "10:42 AM", unread: 2, online: true },
  { id: "c2", name: "Ben Osei", lastMessage: "Can we push the release to Friday?", time: "9:15 AM", unread: 0, online: true },
  { id: "c3", name: "Chen Wei", lastMessage: "Invited you to dns-portal", time: "Yesterday", unread: 0, online: false },
  { id: "c4", name: "Dara Putri", lastMessage: "Uploaded the new mockups to Drive", time: "Yesterday", unread: 1, online: false },
  { id: "c5", name: "Farid Hakim", lastMessage: "Thanks for the update!", time: "Mon", unread: 0, online: false },
  { id: "c6", name: "Hendra Saputra", lastMessage: "Let's sync tomorrow morning.", time: "Mon", unread: 0, online: true },
];

export const chatMessages: Record<string, { id: string; from: "me" | "them"; text: string; time: string }[]> = {
  c1: [
    { id: "m1", from: "them", text: "Hey! Did you get a chance to look at the auth flow PR?", time: "10:30 AM" },
    { id: "m2", from: "me", text: "Yep, looking at it now — the token refresh logic looks solid.", time: "10:35 AM" },
    { id: "m3", from: "them", text: "Great, let me know if anything needs changes.", time: "10:37 AM" },
    { id: "m4", from: "me", text: "Will do. Should be done reviewing in the next hour.", time: "10:40 AM" },
    { id: "m5", from: "them", text: "Sounds good, I'll review the PR today.", time: "10:42 AM" },
  ],
};

export const projectTasks = [
  {
    id: "t1",
    title: "Redesign onboarding flow",
    project: "dns-portal",
    assignee: "Dara Putri",
    priority: "High",
    status: "Todo",
    due: "Sep 3, 2026",
    progress: 0,
  },
  {
    id: "t2",
    title: "Set up CI pipeline for staging",
    project: "alumni-api",
    assignee: "Grace Lim",
    priority: "Medium",
    status: "Todo",
    due: "Sep 5, 2026",
    progress: 0,
  },
  {
    id: "t3",
    title: "Migrate auth service to v2",
    project: "alumni-api",
    assignee: "Ben Osei",
    priority: "High",
    status: "In Progress",
    due: "Sep 1, 2026",
    progress: 60,
  },
  {
    id: "t4",
    title: "Build ecommerce product grid",
    project: "dry-apps-mobile",
    assignee: "Hendra Saputra",
    priority: "Medium",
    status: "In Progress",
    due: "Sep 2, 2026",
    progress: 35,
  },
  {
    id: "t5",
    title: "Write API docs for webhooks",
    project: "laundry-web",
    assignee: "Chen Wei",
    priority: "Low",
    status: "In Review",
    due: "Aug 31, 2026",
    progress: 90,
  },
  {
    id: "t6",
    title: "QA pass on chat notifications",
    project: "dns-services",
    assignee: "Ines Marchetti",
    priority: "Medium",
    status: "In Review",
    due: "Aug 31, 2026",
    progress: 80,
  },
  {
    id: "t7",
    title: "Ship dark mode toggle",
    project: "simplebase",
    assignee: "Amelia Hart",
    priority: "High",
    status: "Done",
    due: "Aug 28, 2026",
    progress: 100,
  },
  {
    id: "t8",
    title: "Fix pagination bug on Users table",
    project: "simplebase",
    assignee: "Farid Hakim",
    priority: "Low",
    status: "Done",
    due: "Aug 27, 2026",
    progress: 100,
  },
];

export const shipments = [
  {
    id: "SDA-01-2401",
    status: "In Transit",
    origin: { country: "Indonesia", location: "CGK Airport", flag: "🇮🇩" },
    destination: { country: "Singapore", location: "SIN Airport", flag: "🇸🇬" },
    cargo: "Consumer Electronics",
    eta: "08:45 AM",
    etaNote: "Today",
    mode: "air",
    weight: "2,450 kg",
    vehicleLabel: "Flight number",
    vehicleNumber: "GA-884",
    progress: 65,
    company: "TechCorp",
    companyCode: "SDA-1001-2401-01",
    priority: true,
    volumeNote: "Top 1% by shipment volume",
    alert: {
      title: "Fragile electronics",
      note: "Keep package sealed until handoff.",
      tags: ["Do not stack", "Keep upright", "Signature required"],
    },
  },
  {
    id: "SDA-02-2402",
    status: "Delayed",
    origin: { country: "Indonesia", location: "Surabaya", flag: "🇮🇩" },
    destination: { country: "Indonesia", location: "Semarang", flag: "🇮🇩" },
    cargo: "Industrial Machinery",
    eta: "11:20 AM",
    etaNote: "Tomorrow",
    mode: "road",
    weight: "8,200 kg",
    vehicleLabel: "Vehicle plate",
    vehicleNumber: "B 9021 TMC",
    progress: 40,
    company: "Wijaya Heavy Industries",
    companyCode: "SDA-1002-2402-01",
    priority: false,
    volumeNote: "Repeat shipper — 24 shipments YTD",
    alert: {
      title: "Oversized load",
      note: "Route requires escort past Kertosono checkpoint.",
      tags: ["Wide load", "Escort required"],
    },
  },
  {
    id: "SDA-03-2403",
    status: "Delivered",
    origin: { country: "Indonesia", location: "Tanjung Priok Port", flag: "🇮🇩" },
    destination: { country: "Singapore", location: "Port of Singapore", flag: "🇸🇬" },
    cargo: "Frozen Seafood",
    eta: "09:15 PM",
    etaNote: "Delivered Yesterday",
    mode: "sea",
    weight: "12,000 kg",
    vehicleLabel: "Vessel",
    vehicleNumber: "MV Nusantara Star",
    progress: 100,
    company: "Ocean Fresh Exports",
    companyCode: "SDA-1003-2403-01",
    priority: false,
    volumeNote: "Cold chain verified",
    alert: {
      title: "Keep frozen",
      note: "Maintain reefer temperature until warehouse handoff.",
      tags: ["Maintain -18°C", "Priority unload"],
    },
  },
  {
    id: "SDA-04-2404",
    status: "On Hold",
    origin: { country: "Malaysia", location: "KUL Airport", flag: "🇲🇾" },
    destination: { country: "Thailand", location: "BKK Airport", flag: "🇹🇭" },
    cargo: "Pharmaceutical Supplies",
    eta: "—",
    etaNote: "Pending customs release",
    mode: "air",
    weight: "640 kg",
    vehicleLabel: "Flight number",
    vehicleNumber: "MH-702",
    progress: 20,
    company: "MediSupply Asia",
    companyCode: "SDA-1004-2404-01",
    priority: true,
    volumeNote: "Regulated goods account",
    alert: {
      title: "Customs hold",
      note: "Additional import documentation requested by BKK customs.",
      tags: ["Temperature sensitive", "Documentation required"],
    },
  },
  {
    id: "SDA-05-2405",
    status: "In Transit",
    origin: { country: "Indonesia", location: "Medan (KNO)", flag: "🇮🇩" },
    destination: { country: "Indonesia", location: "Jakarta (CGK)", flag: "🇮🇩" },
    cargo: "Textile & Apparel",
    eta: "06:30 PM",
    etaNote: "Today",
    mode: "road",
    weight: "3,100 kg",
    vehicleLabel: "Vehicle plate",
    vehicleNumber: "B 7744 KLM",
    progress: 80,
    company: "Nusantara Garment",
    companyCode: "SDA-1005-2405-01",
    priority: false,
    volumeNote: "Standard account",
    alert: null,
  },
  {
    id: "SDA-06-2406",
    status: "Delivered",
    origin: { country: "Singapore", location: "SIN Airport", flag: "🇸🇬" },
    destination: { country: "Indonesia", location: "CGK Airport", flag: "🇮🇩" },
    cargo: "Automotive Parts",
    eta: "—",
    etaNote: "Delivered 2 days ago",
    mode: "air",
    weight: "1,870 kg",
    vehicleLabel: "Flight number",
    vehicleNumber: "SQ-956",
    progress: 100,
    company: "AutoParts Direct",
    companyCode: "SDA-1006-2406-01",
    priority: false,
    volumeNote: "Standard account",
    alert: null,
  },
];

export const events = [
  { id: "e1", title: "Sprint planning", time: "09:00 – 09:45", date: 3, color: "phosphor-green" },
  { id: "e2", title: "Design review — Drive UI", time: "11:00 – 12:00", date: 3, color: "silver-mist" },
  { id: "e3", title: "1:1 with Grace", time: "14:00 – 14:30", date: 6, color: "silver-mist" },
  { id: "e4", title: "Release: v2.4.0", time: "All day", date: 12, color: "phosphor-green" },
  { id: "e5", title: "Client call — Telkomsel", time: "10:00 – 10:30", date: 17, color: "silver-mist" },
  { id: "e6", title: "Security audit due", time: "All day", date: 21, color: "phosphor-green" },
  { id: "e7", title: "Team retro", time: "16:00 – 16:45", date: 27, color: "silver-mist" },
];

export const emailAccounts = [
  { id: "acc1", name: "Arham Khan", email: "hello@arhamkhnz.com", initials: "A" },
  { id: "acc2", name: "Weblabs Studio", email: "team@weblabsstudio.com", initials: "W" },
];

export const emails = [
  {
    id: "em1",
    from: "William Smith",
    fromEmail: "williamsmith@example.com",
    initials: "W",
    to: "Arham Khan",
    cc: "Weblabs Studio",
    subject: "Meeting Tomorrow",
    preview:
      "Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details...",
    time: "about 2 hours ago",
    date: "Wed, 2 Sep 2026, 11:55 PM",
    unread: true,
    pinned: true,
    priority: true,
    folder: "inbox",
    body: [
      "Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's success.",
      "Please come prepared with any questions or insights you may have. Looking forward to our meeting!",
      "Best regards, William",
    ],
    attachments: [
      { name: "studio-admin.fig", size: "21 MB", type: "figma" },
      { name: "features.docx", size: "3.7 MB", type: "doc" },
      { name: "preview.png", size: "2.3 MB", type: "image" },
    ],
  },
  {
    id: "em2",
    from: "Alice Smith",
    fromEmail: "alice.smith@example.com",
    initials: "A",
    to: "Arham Khan",
    cc: "",
    subject: "Re: Project Update",
    preview:
      "Thank you for the project update. It looks great! I've gone through the report, and the progress i...",
    time: "about 3 hours ago",
    date: "Wed, 2 Sep 2026, 10:40 PM",
    unread: false,
    pinned: true,
    priority: true,
    folder: "inbox",
    body: [
      "Thank you for the project update. It looks great! I've gone through the report, and the progress is right on track.",
      "Let me know if there's anything you need from my side before the next milestone.",
      "Best, Alice",
    ],
    attachments: [],
  },
  {
    id: "em3",
    from: "Bob Johnson",
    fromEmail: "bob.johnson@example.com",
    initials: "B",
    to: "Arham Khan",
    cc: "",
    subject: "Weekend Plans",
    preview:
      "Any plans for the weekend? I was thinking of going hiking in the nearby mountains. It's been...",
    time: "1 day ago",
    date: "Tue, 1 Sep 2026, 08:12 PM",
    unread: false,
    pinned: true,
    priority: false,
    folder: "inbox",
    body: [
      "Any plans for the weekend? I was thinking of going hiking in the nearby mountains. It's been a while since we last caught up in person.",
      "Let me know if you're free — would be great to see you.",
    ],
    attachments: [],
  },
  {
    id: "em4",
    from: "Emily Davis",
    fromEmail: "emily.davis@example.com",
    initials: "E",
    to: "Arham Khan",
    cc: "",
    subject: "Re: Question about Budget",
    preview:
      "I have a question about the budget for the upcoming project. It seems like there's a...",
    time: "2 days ago",
    date: "Mon, 31 Aug 2026, 03:05 PM",
    unread: true,
    pinned: true,
    priority: false,
    folder: "inbox",
    body: [
      "I have a question about the budget for the upcoming project. It seems like there's a discrepancy between the initial estimate and the latest figures.",
      "Could we set up a quick call this week to go through the numbers together?",
    ],
    attachments: [],
  },
  {
    id: "em5",
    from: "Michael Wilson",
    fromEmail: "michael.wilson@example.com",
    initials: "M",
    to: "Arham Khan",
    cc: "",
    subject: "Important Announcement",
    preview:
      "I have an important announcement to make during our team meeting. It pertains to a...",
    time: "3 days ago",
    date: "Sun, 30 Aug 2026, 09:20 AM",
    unread: true,
    pinned: false,
    priority: false,
    folder: "inbox",
    body: [
      "I have an important announcement to make during our team meeting. It pertains to a change in our reporting structure starting next quarter.",
      "I'll share the full details tomorrow, but wanted to give you a heads-up beforehand.",
    ],
    attachments: [],
  },
  {
    id: "em6",
    from: "Sarah Brown",
    fromEmail: "sarah.brown@example.com",
    initials: "S",
    to: "Arham Khan",
    cc: "",
    subject: "Re: Feedback on Proposal",
    preview: "Thank you for your feedback on the proposal. It...",
    time: "29 Aug 2026",
    date: "Sat, 29 Aug 2026, 06:48 PM",
    unread: false,
    pinned: false,
    priority: false,
    folder: "inbox",
    body: [
      "Thank you for your feedback on the proposal. It really helped tighten up the scope section.",
      "I've made the revisions you suggested and attached nothing this time — just wanted to confirm before resending the full document.",
    ],
    attachments: [],
  },
];
